version: '3'
services:
  ### Postgres database for Inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kali
    ports:
      - "5431:5431"
    expose:
      - 5431
    command:
      - p 5431

  ### MySQL database for Orders
  db-orders:
    container_name: db-orders
    image: mysql:8.0.36
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_USER: root
      MYSQL_PASSWORD: kali
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - 3306
    command:
      - default-authentication-plugin=mysql_native_password

  ### Postgres database for Products
  db-products:
    container_name: db-products
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kali
    ports:
      - "5431:5431"
    expose:
      - 5431
    command:
      - p 5431

  ###Posgres database for Keycloak
  db-keycloak:
    container_name: db-keycloak
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kali
    ports:
      - "5431:5431"
    expose:
      - 5431
    command:
      - p 5431

  ###Keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: ["start-dev"]
    ports:
      - "8181:8181"
    expose:
      - 8181
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASSWORD: kali
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181
